FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 5001

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["TransactionsApi.csproj", "./"]
RUN dotnet restore "TransactionsApi.csproj"
COPY . .
RUN dotnet build "TransactionsApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TransactionsApi.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TransactionsApi.dll"]