global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'cash-flow-system'

rule_files:
  - "rules/*.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # TransactionsApi instances
  - job_name: 'transactions-api'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'transactions-api-1:5001'
          - 'transactions-api-2:5001'
    scrape_interval: 10s
    scrape_timeout: 5s
    scheme: http

  # ConsolidationsApi instances
  - job_name: 'consolidations-api'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'consolidations-api-1:5002'
          - 'consolidations-api-2:5002'
    scrape_interval: 10s
    scrape_timeout: 5s
    scheme: http

  # HAProxy metrics
  - job_name: 'haproxy'
    static_configs:
      - targets: ['haproxy:8081']
    scrape_interval: 30s

  # RabbitMQ metrics (if available)
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    scrape_interval: 30s

  # KrakenD metrics
  - job_name: 'krakend'
    static_configs:
      - targets: ['krakend:8090']
    scrape_interval: 30s

  # PostgreSQL metrics (via postgres_exporter if available)
  - job_name: 'postgres-transactions'
    static_configs:
      - targets: ['transactions-db:9187']
    scrape_interval: 30s

  - job_name: 'postgres-consolidations'
    static_configs:
      - targets: ['consolidations-db:9187']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093