groups:
  - name: slo_rules
    interval: 30s
    rules:
      # Transaction API SLIs
      - record: transactions_api:availability_rate_5m
        expr: |
          (
            sum(rate(http_requests_received_total{job="transactions-api", code!~"5.."}[5m])) by (instance) /
            sum(rate(http_requests_received_total{job="transactions-api"}[5m])) by (instance)
          ) * 100

      - record: transactions_api:latency_p95_5m
        expr: |
          histogram_quantile(0.95,
            sum(rate(http_request_duration_seconds_bucket{job="transactions-api"}[5m])) by (le, instance)
          ) * 1000

      - record: transactions_api:latency_p99_5m
        expr: |
          histogram_quantile(0.99,
            sum(rate(http_request_duration_seconds_bucket{job="transactions-api"}[5m])) by (le, instance)
          ) * 1000

      - record: transactions_api:error_rate_5m
        expr: |
          (
            sum(rate(http_requests_received_total{job="transactions-api", code=~"5.."}[5m])) by (instance) /
            sum(rate(http_requests_received_total{job="transactions-api"}[5m])) by (instance)
          ) * 100

      - record: transactions_api:throughput_5m
        expr: |
          sum(rate(http_requests_received_total{job="transactions-api"}[5m])) by (instance)

      # Consolidations API SLIs
      - record: consolidations_api:availability_rate_5m
        expr: |
          (
            sum(rate(http_requests_received_total{job="consolidations-api", code!~"5.."}[5m])) by (instance) /
            sum(rate(http_requests_received_total{job="consolidations-api"}[5m])) by (instance)
          ) * 100

      - record: consolidations_api:latency_p95_5m
        expr: |
          histogram_quantile(0.95,
            sum(rate(http_request_duration_seconds_bucket{job="consolidations-api"}[5m])) by (le, instance)
          ) * 1000

      - record: consolidations_api:error_rate_5m
        expr: |
          (
            sum(rate(http_requests_received_total{job="consolidations-api", code=~"5.."}[5m])) by (instance) /
            sum(rate(http_requests_received_total{job="consolidations-api"}[5m])) by (instance)
          ) * 100

      # System Health SLIs
      - record: system:cpu_usage_5m
        expr: |
          100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)

      - record: system:memory_usage_5m
        expr: |
          (
            (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) /
            node_memory_MemTotal_bytes
          ) * 100

      - record: system:disk_usage_5m
        expr: |
          (
            (node_filesystem_size_bytes{fstype!="tmpfs"} - node_filesystem_avail_bytes{fstype!="tmpfs"}) /
            node_filesystem_size_bytes{fstype!="tmpfs"}
          ) * 100

  - name: slo_alerts
    interval: 30s
    rules:
      # Transaction API SLO Alerts (99.9% availability)
      - alert: TransactionAPIHighErrorRate
        expr: |
          (
            sum(rate(http_requests_received_total{job="transactions-api", code=~"5.."}[5m])) /
            sum(rate(http_requests_received_total{job="transactions-api"}[5m]))
          ) * 100 > 0.1
        for: 2m
        labels:
          severity: critical
          service: transactions-api
        annotations:
          summary: "Transaction API error rate is above SLO threshold"
          description: "Error rate is {{ $value }}%"

      - alert: TransactionAPILowAvailability
        expr: |
          (
            sum(rate(http_requests_received_total{job="transactions-api", code!~"5.."}[5m])) /
            sum(rate(http_requests_received_total{job="transactions-api"}[5m]))
          ) * 100 < 99.9
        for: 2m
        labels:
          severity: critical
          service: transactions-api
        annotations:
          summary: "Transaction API availability is below SLO threshold"
          description: "Availability is {{ $value }}%"

      - alert: TransactionAPIHighLatency
        expr: |
          histogram_quantile(0.95,
            sum(rate(http_request_duration_seconds_bucket{job="transactions-api"}[5m])) by (le)
          ) * 1000 > 500
        for: 2m
        labels:
          severity: warning
          service: transactions-api
        annotations:
          summary: "Transaction API latency is above SLO threshold"
          description: "P95 latency is {{ $value }}ms"

      # Consolidations API SLO Alerts (99.5% availability)
      - alert: ConsolidationsAPIHighErrorRate
        expr: |
          (
            sum(rate(http_requests_received_total{job="consolidations-api", code=~"5.."}[5m])) /
            sum(rate(http_requests_received_total{job="consolidations-api"}[5m]))
          ) * 100 > 0.5
        for: 2m
        labels:
          severity: critical
          service: consolidations-api
        annotations:
          summary: "Consolidations API error rate is above SLO threshold"
          description: "Error rate is {{ $value }}%"

      - alert: ConsolidationsAPILowAvailability
        expr: |
          (
            sum(rate(http_requests_received_total{job="consolidations-api", code!~"5.."}[5m])) /
            sum(rate(http_requests_received_total{job="consolidations-api"}[5m]))
          ) * 100 < 99.5
        for: 2m
        labels:
          severity: critical
          service: consolidations-api
        annotations:
          summary: "Consolidations API availability is below SLO threshold"
          description: "Availability is {{ $value }}%"

      # System Resource Alerts
      - alert: HighCPUUsage
        expr: system:cpu_usage_5m > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is {{ $value }}% on instance {{ $labels.instance }}"

      - alert: HighMemoryUsage
        expr: system:memory_usage_5m > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is {{ $value }}% on instance {{ $labels.instance }}"

      - alert: HighDiskUsage
        expr: system:disk_usage_5m > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High disk usage detected"
          description: "Disk usage is {{ $value }}% on instance {{ $labels.instance }}"