apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    orgId: 1
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    basicAuth: false
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 30s
